name: Check Tibia launcher updates

on:
  # schedule:
    # check right after Tuesday server save, and every hour after that for 8 hours to catch hotfixes
    # at minute 5 past every hour from 10 through 18 on Tuesday
    # - cron: '5 10-18 * * TUE'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger update check
        run: |
          curl -Lv ${{ vars.UPDATER_URL }} -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
